# Generated by Django 4.2.2 on 2023-06-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paper_ID', models.CharField(max_length=100)),
                ('Keyword', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paper_ID', models.CharField(max_length=100)),
                ('Title_En', models.TextField(blank=True, null=True)),
                ('Title_Ja', models.EmailField(max_length=100)),
                ('Content_En', models.TextField()),
                ('Content_Ja', models.TextField()),
                ('Search_num', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Pass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paper_ID', models.CharField(max_length=100)),
                ('Reader_ID', models.IntegerField(null=True)),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
